/**
 * Single-language UI strings. The site is English-only since the migration
 * from next-intl, but strings stay centralized here so future copy edits or
 * potential re-introduction of i18n is one file.
 */
export const S = {
  nav: {
    works: 'Works',
    projects: 'Projects',
    blog: 'Blog',
    bio: 'Biography',
    publications: 'Stochastics',
    concerts: 'News',
    contact: 'Contact',
    catalogue: 'Catalogue',
  },
  works: {
    title: 'Works',
    catalog: 'Works catalog',
    instrumentation: 'Instrumentation',
    duration: 'Duration',
    premiere: 'Premiere',
    commissions: 'Commissions',
    ensembles: 'Performers',
    year: 'Year',
    noAudio: 'Audio not available',
    countOne: 'work',
    countOther: 'works',
  },
  home: {
    role: 'Composer and researcher',
    featuredWorks: 'Selected works',
    featuredPosts: 'Selected writing',
    upcomingConcerts: 'Latest news',
    viewAll: 'View all',
    noUpcomingConcerts: 'No recent news.',
  },
  contact: {
    title: 'Contact',
    name: 'Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    send: 'Send message',
    sending: 'Sending…',
    success: 'Message sent successfully.',
    error: 'Error sending message. Please try again.',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'your@email.com',
    subjectPlaceholder: 'Message subject',
    messagePlaceholder: 'Your message…',
  },
  audio: {
    play: 'Play',
    pause: 'Pause',
    loading: 'Loading audio…',
  },
  cv: {
    download: 'Download CV',
  },
  bio: {
    title: 'Biography',
  },
  catalogue: {
    title: 'Catalogue',
    subtitle: 'A comprehensive index of compositions across vocal, instrumental, mixed, and electroacoustic media.',
    sectionLabel: 'List of works',
    featuredLabel: 'Featured work',
    filterAll: 'All',
    filterMixed: 'Vocal · Instrumental · Mixed',
    filterElectro: 'Electroacoustic',
    columnYear: 'Year',
    columnTitle: 'Title',
    columnInstrumentation: 'Instrumentation',
    columnReference: 'Reference',
    listen: 'Listen',
    viewScore: 'View score',
    viewPatch: 'View patch',
    watchVideo: 'Watch video',
    downloadLossless: 'Download lossless',
    empty: 'No entries in this category yet.',
  },
  concerts: {
    title: 'News',
    upcoming: 'Upcoming news',
    past: 'Past news',
    noUpcoming: 'No news scheduled in the near future',
    noPast: 'No past news on record',
  },
  publications: {
    title: 'Stochastics',
    abstract: 'Abstract',
    journal: 'Journal',
    doi: 'DOI',
    download: 'Download PDF',
  },
  projects: {
    title: 'Projects',
  },
  blog: {
    title: 'Blog',
    readMore: 'Read more',
    publishedAt: 'Published on',
  },
  common: {
    backToList: 'Back',
    loading: 'Loading…',
    notFound: 'Not found',
  },
  notFound: {
    title: 'Page not found',
    description: 'The page you are looking for does not exist.',
    back: 'Back to home',
  },
} as const
